---
run_tasks: true
packages:
jedi_service:  jedi
prominic_install_dir: /opt/prominic
jedi_install_dir: "{{ prominic_install_dir }}/jedi"
jedi_install_lib_dir: "{{ jedi_install_dir }}/lib"
jedi_install_jar: "{{ jedi_install_lib_dir }}/jedi.jar"
# path to local jedi artifact.  TODO:  if not found, download instead
jedi_artifact_jar: ./jedi.jar
jedi_cfg_dir: "{{ prominic_install_dir }}/jedi/etc"

# Feel good Variables for Mark to know its in the works :) not implemented yet.
jedi_username: "startcloud"
jedi_password: "{{ 'STARTcloud24@!' | hash('sha1') }}"

jedi_alias:
  enabled: false
  alias: "domino console"
  command: "telnet 0 1910"

# Clear text port
jedi_server_text_port: 1910
# Secure text port
jedi_server_ssltext_port: 1911
# Data port
jedi_server_joes_port: 1710
# Secure data port
jedi_server_ssljoes_port: 1711
# why this
jedi_noteslog: /local/notesdata/noteslog
# online zip 
jedi_online_zip: https://domino-49.prominic.net/jedi-server-private/jedi-github.zip
jedi_local_zip: installers/jedi/archives/jedi.zip
jedi_local_unpack_dir: "{{ role_path }}/files/jedi"
# jar file
jedi_online_jar: https://domino-49.prominic.net/jedi-server-private/jedi-github.jar
jedi_local_jar: installers/jedi/archives/jedi.jar

# Control whether JeDI automatically attempts to start Domino
jedi_domino_autostart: true

# for jediweb
jediweb_install_dir: "{{ prominic_install_dir }}/jediweb"
jediweb_online_zip: https://domino-49.prominic.net/jedi-server-private/test/jediweb-github-temp.zip
jediweb_local_zip: installers/jediweb/archives/jediweb.zip
jediweb_local_unpack_dir: "{{ role_path }}/files/jediweb"


