---
-
  name: "Creating Domino servlet directories"
  ansible.builtin.file:
    mode: '0644'
    path: "{{ item }}"
    state: directory
    owner: "{{ domino_user }}"
    group: "{{ domino_group }}"
  with_items:
    - "{{ domino_home_dir }}/domino/servlet"

-
  name: "Creating Example Servlet Directory in {{ service_home_dir }}"
  ansible.builtin.file:
    mode: '0644'
    path: "{{ item }}"
    state: directory
    owner: "{{ service_user }}"
    group: "{{ service_group }}"
  with_items:
    - "{{ service_home_dir }}/ExampleServlet"

-
  name: "Creating ExampleServlet Class"
  ansible.builtin.shell: "{{ item }}"
  become: true
  become_user: "{{ service_user }}"
  args:
    chdir: "{{ service_home_dir }}"
    executable: /bin/bash
  with_items:
    - "javac -verbose -source 1.8 -target 1.8 -classpath {{ domino_install_basedir }}/notes/latest/linux/jvm/lib/ext/:{{ domino_install_dir }}/ndext/jsdk.jar ExampleServlet.java"

-
  name: "Copying Example Servlet into {{ domino_home_dir }}/domino/servlet"
  ansible.builtin.copy:
    mode: '0644'
    src: "{{ item }}"
    dest: "{{ domino_home_dir }}/domino/servlet"
    remote_src: true
    owner: "{{ domino_user }}"
    group: "{{ domino_group }}"
  with_items:
    - "{{ service_home_dir }}/ExampleServlet.class"

