---
- name: Converge
  hosts: all
  become: true
  vars:
    run_tasks: true
    secrets:
      installer_base_url: "{{ lookup('env', 'INSTALLER_BASE_URL') }}"
      installer_url_user: "{{ lookup('env', 'INSTALLER_URL_USER') }}"
      installer_url_pass: "{{ lookup('env', 'INSTALLER_URL_PASS') }}"
      installer_url_bearer: "{{ lookup('env', 'INSTALLER_URL_BEARER') }}"
    completed_dir: /vagrant/completed
    is_additional_server: false
    user_safe_id: SAFE.IDS
    org_safe_ids:
      - ORG-SAFE.IDS
  roles:
    - role: domino_cross_certify
