---
nomadweb_archive: nomad-server-1.0.10-for-domino-12.0.2-linux.tgz
nomadweb_version: 1.0.10
nomadweb_debug: false
nomadweb_force: false
installer_url_app_path: "Super.Human.Installer/Nomad"
domino_nomadweb_port_forwards:
  -
    guest: 9443
    url: "nomadweb"
domino_nomadweb_proxy_url: "{{ domino_nomadweb_port_forwards[0].url }}.{{ settings.hostname }}.{{ settings.domain }}"
