---
run_tasks: true

voltmx_go_version: 2.1.1

# Download File
voltmx_go_installer_archive: "HCLVoltMXGO_Plugin_Installer_Tool_Linux_V{{ voltmx_go_version }}.tar.gz"
installer_file:
  app: VoltMXGo
  version: "{{ voltmx_go_version }}"
  variant: release
  name: "{{ voltmx_go_installer_archive }}"

# Extracted VoltMX Go Plugin Installer
voltmx_go_plugin_installer_bin: "VoltMXGoInstallationTool-9.5.18.3.bin"

## VoltMX Go Installer
voltmx_go_install_dir: "{{ voltmx_installation_dir }}/VoltMXGoPluginInstaller"
voltmx_go_installer_bin: "VoltMXGoPluginInstaller"

install_voltmx_go_plugin: true
