---
run_tasks: true
show_help: true
debug_autoconfigure: false
domino_server_id: "server.id"
use_domino_server_id: true
origin_server: ""
origin_server_ip: ""
domino_config:
  delete_input_file_after_processing: "false"
  start_server_after_configuration: "true"